adapter: mysql2
host: <%= ENV["TODOLIST_DB_HOST"] %>
port: <%= ENV["TODOLIST_DB_PORT"] %>
database: <%= ENV["TODOLIST_DB_NAME"] %>
username: <%= ENV["TODOLIST_DB_USER"] %>
password: <%= ENV["TODOLIST_DB_PASS"] %>
