adapter: mysql2
host: <%= ENV["RUTODO_DB_HOST"] %>
port: <%= ENV["RUTODO_DB_PORT"] %>
database: <%= ENV["RUTODO_DB_NAME"] %>
username: <%= ENV["RUTODO_DB_USER"] %>
password: <%= ENV["RUTODO_DB_PASS"] %>
